/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.118
 * Generated at: 2026-06-22 00:55:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.mvc.bean.LocationSizeBean;
import com.mvc.dao.LocationSizeDAO;
import com.mvc.bean.LocationBean;
import com.mvc.dao.LocationDAO;
import java.util.List;
import java.util.ArrayList;
import com.mvc.bean.SizeBean;
import com.mvc.dao.SizeDAO;

public final class AssignLocationSize_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.LinkedHashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Header.jsp", Long.valueOf(1782088629395L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(11);
    _jspx_imports_classes.add("com.mvc.bean.LocationSizeBean");
    _jspx_imports_classes.add("com.mvc.dao.LocationSizeDAO");
    _jspx_imports_classes.add("com.mvc.bean.LocationBean");
    _jspx_imports_classes.add("com.mvc.dao.LocationDAO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.mvc.bean.SizeBean");
    _jspx_imports_classes.add("com.mvc.dao.SizeDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>::Admin Home::</title>\r\n");
      out.write("<script>\r\n");
      out.write("function goToPage(selectObj)\r\n");
      out.write("{\r\n");
      out.write("    if(selectObj.value != \"\")\r\n");
      out.write("    {\r\n");
      out.write("        window.location.href = selectObj.value;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("	</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h1 align =\"center\">Admin Home</h1><br>\r\n");
      out.write("	");
 
	String username =(String)session.getAttribute("username");
	
      out.write("\r\n");
      out.write("	<h2 align =\"left\">Welcome  ");
      out.print(username );
      out.write("</h2><br>\r\n");
      out.write("	\r\n");
      out.write("	<select onchange=\"goToPage(this)\">\r\n");
      out.write("    <option value=\"\"selected disabled>Settings</option>\r\n");
      out.write("    <option value=\"AddLocation.jsp\">Add Location</option>\r\n");
      out.write("    <option value=\"ViewLocation.jsp\">View Location</option>\r\n");
      out.write("    <option value=\"AddBillSize.jsp\">Add Billboard Size</option>\r\n");
      out.write("    <option value=\"ViewSize.jsp\">View Billboard Size</option>\r\n");
      out.write("    <option value=\"AssignLocationSize.jsp\">Assign location and Size</option>\r\n");
      out.write("	</select>&nbsp;&nbsp;\r\n");
      out.write("	\r\n");
      out.write("	<select onchange=\"goToPage(this)\">\r\n");
      out.write("    <option value=\"\"selected disabled>Customer</option>\r\n");
      out.write("    <option value=\"AddCustomer.jsp\">Add Customer</option>\r\n");
      out.write("    <option value=\"ViewCustomer.jsp\">View Customer</option>\r\n");
      out.write("	</select>&nbsp;&nbsp;\r\n");
      out.write("	\r\n");
      out.write("	<select onchange=\"goToPage(this)\">\r\n");
      out.write("    <option value=\"\"selected disabled>Billboard</option>\r\n");
      out.write("    <option value=\"Billboardpurchase.jsp\">Purchase Billboard</option>\r\n");
      out.write("    <option value=\"ViewPurchase.jsp\">Purchase History</option>\r\n");
      out.write("	</select>&nbsp;&nbsp;\r\n");
      out.write("	\r\n");
      out.write("	<select onchange=\"goToPage(this)\">\r\n");
      out.write("    <option value=\"\" selected disabled>Inspector</option>\r\n");
      out.write("    <option value=\"AddInspector.jsp\">Add Inspector</option>\r\n");
      out.write("    <option value=\"ViewInspector.jsp\">View Inspector</option>\r\n");
      out.write("    <option value=\"workallocation.jsp\">Allocate work</option>\r\n");
      out.write("    <option value=\"ViewWorkallocation.jsp\">View Allocated work</option>\r\n");
      out.write("	</select>&nbsp;&nbsp;\r\n");
      out.write("	\r\n");
      out.write("	<select onchange=\"goToPage(this)\">\r\n");
      out.write("    <option value=\"\" selected disabled>Payment</option>\r\n");
      out.write("    <option value=\"AddPayment.jsp\">Add Payment</option>\r\n");
      out.write("    <option value=\"ViewPayment.jsp\">View Payments</option>\r\n");
      out.write("	</select>&nbsp;&nbsp;\r\n");
      out.write("	\r\n");
      out.write("	<a href =\"Logout.jsp\">Logout</a><br>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("			function valForm()\r\n");
      out.write("			{	\r\n");
      out.write("				\r\n");
      out.write("				if(document.assignLocSizeForm.locationname.value==\"\")\r\n");
      out.write("				{\r\n");
      out.write("					alert(\"Enter Location Name\");\r\n");
      out.write("					document.assignLocSizeForm.locationname.focus();\r\n");
      out.write("					return false;\r\n");
      out.write("				}\r\n");
      out.write("				if(document.assignLocSizeForm.locationaddress.value==\"\")\r\n");
      out.write("				{\r\n");
      out.write("					alert(\"Enter Location Address\");\r\n");
      out.write("					document.assignLocSizeForm.locationaddress.focus();\r\n");
      out.write("					return false;\r\n");
      out.write("				}\r\n");
      out.write("				document.assignLocSizeForm.submit();			\r\n");
      out.write("			}\r\n");
      out.write("	</script>\r\n");
      out.write("	");

	List<LocationBean> locations = LocationDAO.getAllLocation();
	List<SizeBean>sizes = SizeDAO.getAllSize();
	
      out.write("\r\n");
      out.write("		\r\n");
      out.write("	<h1 align =\"center\">ASSIGN LOCATION AND SIZE</h1>\r\n");
      out.write("	\r\n");
      out.write("	<form name=\"assignLocSizeForm\" method=\"post\" action=\"AssignLocationSizeAction.jsp\" >\r\n");
      out.write("	\r\n");
      out.write("		Location:<select name =\"locationId\">\r\n");
      out.write("		\r\n");
      out.write("		");
 for(LocationBean location:locations){
      out.write("\r\n");
      out.write("					<option value =\"");
      out.print( location.getLocationId());
      out.write('"');
      out.write('>');
      out.print(location.getLocationName());
      out.write("</option>\r\n");
      out.write("		");
} 
      out.write("\r\n");
      out.write("		</select><br><br>\r\n");
      out.write("		\r\n");
      out.write("		Size:<select name=sizeId>\r\n");
      out.write("		\r\n");
      out.write("		");
for(SizeBean size :sizes) {
      out.write("\r\n");
      out.write("				<option value =\"");
      out.print(size.getSizeId());
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(size.getBillboardSize() );
      out.write("</option>\r\n");
      out.write("		");
} 
      out.write("\r\n");
      out.write("		</select><br><br>\r\n");
      out.write("		\r\n");
      out.write("		Price:<input type = \"number\" name =\"price\"/>\r\n");
      out.write("		\r\n");
      out.write("		Availability Status:<select name =\"availability\">\r\n");
      out.write("							<option>Available</option>\r\n");
      out.write("							<option>Not Available</option>\r\n");
      out.write("							</select>\r\n");
      out.write("		<br> <input type=\"submit\" value=\"ADD\" onclick =\"return valForm();\"/>\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
